.TH "deprecated" 3 "Thu Aug 6 2026 16:42:08" "Version 1.0.30" "libusb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 
.PP


.PP
.IP "\fBGlobal \fBlibusb_get_port_path\fP (\fBlibusb_context\fP *ctx, \fBlibusb_device\fP *dev, uint8_t *port_numbers, uint8_t port_numbers_len)
.IP "" 1c
Please use \fBlibusb_get_port_numbers()\fP instead\&. 

.PP

