.TH "libusb_init_option::[union].value" 3 "Version 1.0.30" "libusb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libusb_init_option::[union].value
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBival\fP"
.br
.RI "An integer value used by the option\&. "
.ti -1c
.RI "\fBlibusb_log_cb\fP \fBlog_cbval\fP"
.br
.RI "A log callback used by the option\&. "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for libusb from the source code\&.
