.TH "libusb_init_option" 3 "Version 1.0.30" "libusb" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libusb_init_option \- Structure used for setting options through \fBlibusb_init_context\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <libusb\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "union \fB[union]\&.value\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "enum \fBlibusb_option\fP \fBoption\fP"
.br
.RI "Which option to set\&. "
.ti -1c
.RI "\fBunion \fP \fBvalue\fP"
.br
.RI "The value used by the option (if applicable)\&. "
.in -1c
.SH "Detailed Description"
.PP 
Structure used for setting options through \fBlibusb_init_context\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libusb from the source code\&.
