plugins {
    alias(libs.plugins.android.application)
}

android {
// Redirigir la carpeta build a /tmp
    project.layout.buildDirectory.set(file("/tmp/mini"))
    namespace 'com.diamon.mini'
    compileSdk {
        version = release(37) {
            minorApiLevel = 0
        }
    }

    buildToolsVersion '37.0.0'
    ndkVersion '30.0.14904198 rc1'

    defaultConfig {
        applicationId "com.diamon.mini"
        minSdk 23
        targetSdk 37
        versionCode 4
        versionName "1.0.0-pre.8"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters "arm64-v8a"
        }
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '4.1.2'
        }
    }

packaging {
        jniLibs {
            useLegacyPackaging = true
        }
        doNotStrip "**/*.so"
    }

    buildFeatures {
        viewBinding true
        resValues true
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material
    implementation(libs.usb.serial.for1.android)
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
}